### ISSUE TITLE
Get HTML method not implemented

### ISSUE THREAD

**Issue by racostae** [headspinio/appium-roku-driver#44]
Currently there's no way to get the content of an element. I tried with the `getHTML` webdriverio method, but it throws me this error: 
![image](https://user-images.githubusercontent.com/16063417/206249193-d2dee05e-5982-4136-88b0-5b515fad7422.png)

**Comment by jlipps** [comment]
`getHTML` is not supported on the roku driver since there is no HTML  or ability to execute javascript. instead use the standard [getPageSource](https://webdriver.io/docs/api/webdriver#getpagesource) command.
