### ISSUE TITLE
Unable to launch the Roku tv app using Appium 2.0 Roku driver

### ISSUE THREAD

**Issue by srinuchinta** [headspinio/appium-roku-driver#66]
Hi Team, 

Unable to launch the Roku tv app using Appium 2.0 with below capabilities. Planning to automation the Roku TV app using appium with java language. Tried with Appium desktop / Script as well.
Could you please help me to resolve the Roku Tv issue

{
  "appium:rokuUser": "rokudev",
  "appium:rokuPass": 1111,
  "appium: rokuHost": "192.168.99.74",
  "appium:rokuEcpPort": 8060,
  "platformName": "Roku",
  "appium:automationName": "Roku",
  "appium:rokuHeaderHost": "192.168.99.74",
  "appium:rokuWebPort": 80,
  "appium:platformVersion": "11",
  "appium:app": "dev"
}
<img width="1459" alt="Screenshot 2023-10-21 at 11 21 17 AM" src="https://github.com/headspinio/appium-roku-driver/assets/23380952/99e43b58-c25f-4508-984f-ca3fbc052ed6">

<img width="1426" alt="Screenshot 2023-10-21 at 11 21 38 AM" src="https://github.com/headspinio/appium-roku-driver/assets/23380952/2a522764-3c3d-4d56-9014-02ad548005b8">

**Comment by srinuchinta** [comment]
Appium server is running on 127.0.0.1 and port is 4723

**Comment by jlipps** [comment]
This is expected. The Roku driver requires Appium 2. Please follow the installation instructions in the README.

**Comment by srinuchinta** [comment]
Hi Sir,
i am using Appium 2.0 and Java 11.
using above capabilities and trying to launch the App in Roku using Appium desktop (version: 1.22).
But no luck app is not launching and Roku logs are not showing in Appium server.
Could you help me to reslove the issue.

**Comment by srinuchinta** [comment]
> Hi Sir, i am using Appium 2.0 and Java 11. using above capabilities and trying to launch the App in Roku using Appium desktop (version: 1.22). But no luck app is not launching and Roku logs are not showing in Appium server. Could you help me to reslove the issue.
