### ISSUE TITLE
Hi Sir,

### ISSUE THREAD

**Issue by srinuchinta** [headspinio/appium-roku-driver#67]
Hi Sir,
i am using Appium 2.0 and Java 11.
using above capabilities and trying to launch the App in Roku using Appium desktop (version: 1.22).
But no luck app is not launching and Roku logs are not showing in Appium server.
Could you help me to reslove the issue.

_Originally posted by @srinuchinta in https://github.com/headspinio/appium-roku-driver/issues/66#issuecomment-1775927783_

**Comment by KazuCocoa** [comment]
Appium desktop (version: 1.22) may not have any compatibility with Appium 2, btw.
Sharing the appium server log might help us to take a look at the cause.

**Comment by jlipps** [comment]
Yes, this driver requires Appium 2. Appium Desktop has been discontinued for years now as well, and should not be used.
