### ISSUE TITLE
i am using Appium 2.0 and Java 11. using below capabilities and trying to launch the App in RokuTV using Appium desktop (version: 1.22). But no luck app is not launching and Roku logs are not showing in Appium server. Could you help me to reslove the issue.

### ISSUE THREAD

**Issue by srinuchinta** [headspinio/appium-roku-driver#68]
Hi Team,

Unable to launch the Roku tv app using Appium 2.0 with below capabilities. Planning to automation the Roku TV app using appium with java language. Tried with Appium desktop / Script as well.
Could you please help me to resolve the Roku Tv issue

{
"appium:rokuUser": "rokudev",
"appium:rokuPass": 1111,
"appium: rokuHost": "192.168.99.74",
"appium:rokuEcpPort": 8060,
"platformName": "Roku",
"appium:automationName": "Roku",
"appium:rokuHeaderHost": "192.168.99.74",
"appium:rokuWebPort": 80,
"appium:platformVersion": "11",
"appium:app": "dev"
}

**Comment by KazuCocoa** [comment]
Could you share the full appium log?

**Comment by srinuchinta** [comment]
Hi Sir,
I have used below capabilities to launch the App in Roku streaming stick. But no luck.
App is installed in the Roku streaming stick.
Appium 2.0 version
Appium desktop (version: 1.22)
Please find the appium server log pdf file.
Could you please help me.

<img width="1454" alt="Screenshot 2023-10-24 at 9 51 21 AM" src="https://github.com/headspinio/appium-roku-driver/assets/23380952/1a525fd4-4229-44a4-b40d-ffd26324cbd2">
<img width="1451" alt="Screenshot 2023-10-24 at 9 54 52 AM" src="https://github.com/headspinio/appium-roku-driver/assets/23380952/8412f106-753f-478d-bab4-9b4baa64112f">
[appium-server-logs.pdf](https://github.com/headspinio/appium-roku-driver/files/13121751/appium-server-logs.pdf)

**Comment by srinuchinta** [comment]
[info] [35m[HTTP][39m Waiting until the server is closed
[info] [35m[HTTP][39m Received server close event
[info] [35m[Appium][39m Welcome to Appium v1.22.3
[info] [35m[Appium][39m Non-default server args:
[info] [35m[Appium][39m   address: 127.0.0.1
[info] [35m[Appium][39m   relaxedSecurityEnabled: true
[info] [35m[Appium][39m   allowInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m   denyInsecure: {
[info] [35m[Appium][39m   }
[info] [35m[Appium][39m Appium REST http interface listener started on 127.0.0.1:4723[info] [35m[HTTP][39m [37m-->[39m [37mPOST[39m [37m/wd/hub/session[39m
[info] [35m[HTTP][39m [90m{"capabilities":{"alwaysMatch":{"appium:rokuUser":"rokudev","appium:rokuPass":1111,"appium: rokuHost":"192.168.99.74","appium:rokuEcpPort":8060,"platformName":"Roku","appium:automationName":"Roku","appium:rokuHeaderHost":"192.168.99.74","appium:rokuWebPort":80,"appium:platformVersion":"11","appium:appId":"dev","appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"appium:rokuUser":"rokudev","appium:rokuPass":1111,"appium: rokuHost":"192.168.99.74","appium:rokuEcpPort":8060,"platformName":"Roku","appium:automationName":"Roku","appium:rokuHeaderHost":"192.168.99.74","appium:rokuWebPort":80,"appium:platformVersion":"11","appium:appId":"dev","appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}[39m
[debug] [35m[W3C][39m Calling AppiumDriver.createSession() with args: [{"appium:rokuUser":"rokudev","appium:rokuPass":1111,"appium: rokuHost":"192.168.99.74","appium:rokuEcpPort":8060,"platformName":"Roku","appium:automationName":"Roku","appium:rokuHeaderHost":"192.168.99.74","appium:rokuWebPort":80,"appium:platformVersion":"11","appium:appId":"dev","appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"appium:rokuUser":"rokudev","appium:rokuPass":1111,"appium: rokuHost":"192.168.99.74","appium:rokuEcpPort":8060,"platformName":"Roku","appium:automationName":"Roku","appium:rokuHeaderHost":"192.168.99.74","appium:rokuWebPort":80,"appium:platformVersion":"11","appium:appId":"dev","appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[debug] [35m[BaseDriver][39m Event 'newSessionRequested' logged at 1698166477915 (09:54:37 GMT-0700 (Pacific Daylight Time))
[debug] [35m[Appium][39m Error: Cannot find module 'appium-roku-driver'
[debug] [35m[Appium][39m Require stack:
[debug] [35m[Appium][39m - /Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/build/lib/appium.js
[debug] [35m[Appium][39m - /Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/build/lib/main.js
[debug] [35m[Appium][39m - /Applications/Appium Server GUI.app/Contents/Resources/app/dist/main.js
[debug] [35m[Appium][39m - 
[debug] [35m[Appium][39m     at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
[debug] [35m[Appium][39m     at Function.o._resolveFilename (electron/js2c/browser_init.js:257:921)
[debug] [35m[Appium][39m     at Module._load (internal/modules/cjs/loader.js:844:27)
[debug] [35m[Appium][39m     at Function.Module._load (electron/js2c/asar.js:779:28)
[debug] [35m[Appium][39m     at Module.require (internal/modules/cjs/loader.js:1023:19)
[debug] [35m[Appium][39m     at require (internal/modules/cjs/helpers.js:77:18)
[debug] [35m[Appium][39m     at AppiumDriver.getDriverAndVersionForCaps (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/lib/appium.js:252:24)
[debug] [35m[Appium][39m     at AppiumDriver.createSession (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/lib/appium.js:340:66)
[debug] [35m[Appium][39m     at commandExecutor (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
[debug] [35m[Appium][39m     at AppiumDriver.executeCommand (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:349:15)
[debug] [35m[Appium][39m     at AppiumDriver.executeCommand (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/lib/appium.js:549:26)
[debug] [35m[Appium][39m     at asyncHandler (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:34)
[debug] [35m[Appium][39m     at /Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:423:15
[debug] [35m[Appium][39m     at Layer.handle [as handle_request] (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [35m[Appium][39m     at next (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[debug] [35m[Appium][39m     at Route.dispatch (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[debug] [35m[Appium][39m     at Layer.handle [as handle_request] (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [35m[Appium][39m     at /Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:281:22
[debug] [35m[Appium][39m     at Function.process_params (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [35m[Appium][39m     at next (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [35m[Appium][39m     at logger (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/morgan/index.js:144:5)
[debug] [35m[Appium][39m     at Layer.handle [as handle_request] (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [35m[Appium][39m     at trim_prefix (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:317:13)
[debug] [35m[Appium][39m     at /Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:284:7
[debug] [35m[Appium][39m     at Function.process_params (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:335:12)
[debug] [35m[Appium][39m     at next (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:275:10)
[debug] [35m[Appium][39m     at /Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/body-parser/lib/read.js:130:5
[debug] [35m[Appium][39m     at invokeCallback (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/raw-body/index.js:224:16)
[debug] [35m[BaseDriver][39m Event 'newSessionStarted' logged at 1698166477928 (09:54:37 GMT-0700 (Pacific Daylight Time))
[debug] [35m[W3C][39m Encountered internal error running command: Error: Could not load a driver for automationName 'Roku' and platformName 'Roku'. Please verify your Appium installation
[debug] [35m[W3C][39m     at AppiumDriver.getDriverAndVersionForCaps (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/lib/appium.js:268:11)
[debug] [35m[W3C][39m     at AppiumDriver.createSession (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/lib/appium.js:340:66)
[debug] [35m[W3C][39m     at commandExecutor (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:335:9)
[debug] [35m[W3C][39m     at AppiumDriver.executeCommand (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/basedriver/driver.js:349:15)
[debug] [35m[W3C][39m     at AppiumDriver.executeCommand (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/lib/appium.js:549:26)
[debug] [35m[W3C][39m     at asyncHandler (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:297:34)
[debug] [35m[W3C][39m     at /Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/appium-base-driver/lib/protocol/protocol.js:423:15
[debug] [35m[W3C][39m     at Layer.handle [as handle_request] (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [35m[W3C][39m     at next (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/route.js:137:13)
[debug] [35m[W3C][39m     at Route.dispatch (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/route.js:112:3)
[debug] [35m[W3C][39m     at Layer.handle [as handle_request] (/Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/layer.js:95:5)
[debug] [35m[W3C][39m     at /Applications/Appium Server GUI.app/Contents/Resources/app/node_modules/appium/node_modules/express/lib/router/index.js:281:22

**Comment by srinuchinta** [comment]
<img width="1050" alt="Screenshot 2023-10-24 at 10 03 35 AM" src="https://github.com/headspinio/appium-roku-driver/assets/23380952/730b5096-323a-4bcb-a137-48e90ad7e89d">
appium roku driver folder available in the system path : /Users/a2065873831/.appium/node_modules/@headspinio/appium-roku-driver

**Comment by srinuchinta** [comment]
<img width="883" alt="Screenshot 2023-10-24 at 10 20 30 AM" src="https://github.com/headspinio/appium-roku-driver/assets/23380952/09027294-1f14-4a60-9224-04e95b74d45b">

**Comment by KazuCocoa** [comment]
The desktop app tried to connect to appium 1.22.3. Please start a session with an appium client without appium desktop/inspector.

**Comment by srinuchinta** [comment]
Hi @KazuCocoa Sir,
not sure the driver name what exactly i need to pass instead of WebDriver and respective  import statement for Roku driver.
Could you please me to share the Capability details for java (version 11 ) with Roku driver.

				caps.setCapability("appium:rokuUser", "rokudev");
			    caps.setCapability("appium:rokuPass", 1111);
			    caps.setCapability("appium: rokuHost", "192.168.99.74");
			    caps.setCapability("appium:rokuEcpPort", 8060);
				caps.setCapability("platformName", "Roku");
				caps.setCapability("appium:automationName", "Roku");
				caps.setCapability("appium:rokuHeaderHost", "192.168.99.74");
				caps.setCapability("appium:rokuWebPort", 80);
				caps.setCapability("appium:platformVersion", "11");
				caps.setCapability("app", "dev");
				driver = new WebDriver(new URL("http://0.0.0.0:"+"4723"+"/wd/hub"), caps);

<img width="695" alt="Screenshot 2023-10-25 at 9 30 09 AM" src="https://github.com/headspinio/appium-roku-driver/assets/23380952/a7b11645-60ab-42f8-a436-8bf857c6202a">

**Comment by srinuchinta** [comment]
programmatically to initiate the Roku driver after run the appium command in mac terminal.
Please provide the Capability details for java (version 11 ) with Roku driver and import statement for Roku driver.

**Comment by jlipps** [comment]
The Roku driver requires appium 2. Please follow the instructions in the readme.
