### ISSUE TITLE
add semantics release to make release automate

### ISSUE THREAD

**Issue by KazuCocoa** [headspinio/appium-roku-driver#72]
As the same as other appium drivers. Let me do it later cc @jlipps

**Comment by jlipps** [comment]
worried that without proper e2e tests in CI this might not be a good idea

**Comment by KazuCocoa** [comment]
Oh.. i thought the unit test covered input/output in this driver by emulating the response of the device (chroemdriver), but almost nothing.
Hm, then auto release is not good
